name: Keep Supabase Alive

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -X GET "https://quoder-green.vercel.app/api/keep-alive?key=${{ secrets.KEEP_ALIVE_SECRET }}"
